-- SQL-Skript zum Erzeugen der AMS-Datenbank in Oracle
-- Aktuelle Version vom 21.10.2013
-- Änderungen von C1-WPS

-- DROP Tables
DROP TABLE AMS_FILTERCOND_FILTERCOND;
DROP TABLE AMS_FILTERCOND_NEGATION;
DROP TABLE AMS_FILTER_WATCHDOG;
DROP TABLE AMS_FILTER_TIMEBASED;
DROP TABLE AMS_FLAG;
DROP TABLE AMS_DEFMESSAGETEXT;
DROP TABLE AMS_GROUPS;
DROP TABLE AMS_TBFILTER_FILTERCOND;
DROP TABLE AMS_FILTERCOND_PROPCOMPARE;
DROP TABLE AMS_FILTER_FILTERACTION;
DROP TABLE AMS_FILTERACTION;
DROP TABLE AMS_FILTERACTIONTYPE;
DROP TABLE AMS_TOPIC;
DROP TABLE AMS_FILTER_FILTERCONDITION;
DROP TABLE AMS_FILTER;
DROP TABLE AMS_FILTERCOND_CONJ_COMMON;
DROP TABLE AMS_FILTERCONDITION_PV;
DROP TABLE AMS_FILTERCOND_TIMEBASED;
DROP TABLE AMS_FILTERCOND_ARRSTRVAL;
DROP TABLE AMS_FILTERCOND_ARRSTR;
DROP TABLE AMS_FILTERCONDITION_STRING;
DROP TABLE AMS_FILTERCONDITIONTYPE;
DROP TABLE AMS_USERGROUP_USER;
DROP TABLE AMS_USERGROUP;
DROP TABLE AMS_USER;
DROP TABLE AMS_FILTERCOND_JUNCTION;
DROP TABLE AMS_FILTERCONDITION;

-- Synchronisationstabellen

DROP TABLE AMS_FILTERCOND_JUNCTION_SYN;
DROP TABLE AMS_FILTERCOND_FILTERCOND_SYN;
DROP TABLE AMS_FILTERCOND_NEGATION_SYN;
DROP TABLE AMS_FILTER_WATCHDOG_SYN;
DROP TABLE AMS_FILTER_TIMEBASED_SYN;
DROP TABLE AMS_FILTERCOND_PROPCOMPARE_SYN;
DROP TABLE AMS_USERGROUP_SYN;
DROP TABLE AMS_FILTER_FILTERACTION_SYN;
DROP TABLE AMS_FILTERACTION_SYN;
DROP TABLE AMS_FILTERACTIONTYPE_SYN;
DROP TABLE AMS_TOPIC_SYN;
DROP TABLE AMS_FILTER_FILTERCONDITION_SYN;
DROP TABLE AMS_FILTER_SYN;
DROP TABLE AMS_FILTERCOND_CONJ_COMMON_SYN;
DROP TABLE AMS_FILTERCONDITION_PV_SYN;
DROP TABLE AMS_FILTERCOND_TIMEBASED_SYN;
DROP TABLE AMS_FILTERCOND_ARRSTRVAL_SYN;
DROP TABLE AMS_FILTERCOND_ARRSTR_SYN;
DROP TABLE AMS_FILTERCONDITION_STRING_SYN;
DROP TABLE AMS_FILTERCONDITION_SYN;
DROP TABLE AMS_FILTERCONDITIONTYPE_SYN;
DROP TABLE AMS_USERGROUP_USER_SYN;
DROP TABLE AMS_USER_SYN;

-- Create Configuration Tables

CREATE TABLE AMS_FILTERCOND_FILTERCOND 
(
    iFilterConditionId NUMBER(11,0) NOT NULL ENABLE, 
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE
);

CREATE TABLE AMS_FILTERCOND_NEGATION 
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    INEGATEDFCREF NUMBER(11,0) NOT NULL ENABLE
);

CREATE TABLE AMS_USER 
(
    IUSERID NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CUSERNAME VARCHAR2(128), 
    CEMAIL VARCHAR2(128), 
    CMOBILEPHONE VARCHAR2(64), 
    CPHONE VARCHAR2(64), 
    CSTATUSCODE VARCHAR2(32), 
    CCONFIRMCODE VARCHAR2(32), 
    SACTIVE NUMBER(6,0), 
    SPREFERREDALARMINGTYPERR NUMBER(6,0), 
     PRIMARY KEY (IUSERID) ENABLE
);

CREATE TABLE AMS_USERGROUP 
(
    IUSERGROUPID NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CUSERGROUPNAME VARCHAR2(128), 
    SMINGROUPMEMBER NUMBER(6,0), 
    ITIMEOUTSEC NUMBER(11,0), 
    SACTIVE NUMBER(6,0), 
     PRIMARY KEY (IUSERGROUPID) ENABLE
);

CREATE TABLE AMS_USERGROUP_USER 
(
    IUSERGROUPREF NUMBER(11,0) NOT NULL ENABLE, 
    IUSERREF NUMBER(11,0) NOT NULL ENABLE, 
    IPOS NUMBER(11,0) NOT NULL ENABLE, 
    SACTIVE NUMBER(6,0), 
    CACTIVEREASON VARCHAR2(128), 
    TTIMECHANGE NUMBER(14,0), 
     PRIMARY KEY (IUSERGROUPREF, IUSERREF) ENABLE
);

CREATE TABLE AMS_FILTERCONDITIONTYPE 
(
    IFILTERCONDITIONTYPEID NUMBER(11,0), 
    CNAME VARCHAR2(128), 
    CCLASS VARCHAR2(256), 
    CCLASSUI VARCHAR2(256), 
    PRIMARY KEY (IFILTERCONDITIONTYPEID) ENABLE
);

CREATE TABLE AMS_FILTERCONDITION_STRING 
(   
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CKEYVALUE VARCHAR2(16), 
    SOPERATOR NUMBER(6,0), 
    CCOMPVALUE VARCHAR2(128)
);

CREATE TABLE AMS_FILTERCOND_ARRSTR 
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CKEYVALUE VARCHAR2(16), 
    SOPERATOR NUMBER(6,0)
);

CREATE TABLE AMS_FILTERCOND_ARRSTRVAL 
(   
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CCOMPVALUE VARCHAR2(128)
);

CREATE TABLE AMS_FILTERCOND_TIMEBASED
(   
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CSTARTKEYVALUE VARCHAR2(16), 
    SSTARTOPERATOR NUMBER(6,0), 
    CSTARTCOMPVALUE VARCHAR2(128), 
    CCONFIRMKEYVALUE VARCHAR2(16), 
    SCONFIRMOPERATOR NUMBER(6,0), 
    CCONFIRMCOMPVALUE VARCHAR2(128), 
    STIMEPERIOD NUMBER(6,0), 
    STIMEBEHAVIOR NUMBER(6,0)
);

CREATE TABLE AMS_FILTERCONDITION_PV
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CPVCHANNELNAME VARCHAR2(128), 
    SSUGGESTEDPVTYPEID NUMBER(6,0), 
    SOPERATORID NUMBER(6,0), 
    CCOMPVALUE VARCHAR2(128)
);

CREATE TABLE AMS_FILTERCOND_CONJ_COMMON
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    IFIRSTFILTERCONDITIONREF NUMBER(11,0) NOT NULL ENABLE, 
    ISECONDFILTERCONDITIONREF NUMBER(11,0) NOT NULL ENABLE, 
    IOPERAND NUMBER(6,0)
);

CREATE TABLE AMS_FILTERCONDITION
(
    iFilterConditionId NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CNAME VARCHAR2(128), 
    CDESC VARCHAR2(256), 
    IFILTERCONDITIONTYPEREF NUMBER(11,0), 
     PRIMARY KEY (iFilterConditionId) ENABLE
);

CREATE TABLE AMS_FILTERCOND_JUNCTION
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    operator VARCHAR2(3) NOT NULL ENABLE, 
    CONSTRAINT AMS_FILTERCOND_JUNCTION_PK PRIMARY KEY (iFilterConditionRef) ENABLE, 
    CONSTRAINT AMS_FILTERCOND_JUNCTION_FK FOREIGN KEY (iFilterConditionRef)
    REFERENCES AMS_FILTERCONDITION (iFilterConditionId) ON DELETE CASCADE ENABLE
);

CREATE TABLE AMS_FILTER
(
    IFILTERID NUMBER(11,0), 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CNAME VARCHAR2(128), 
    CDEFAULTMESSAGE VARCHAR2(1024), 
    CFILTERTYPE VARCHAR2(100) DEFAULT 'default' NOT NULL ENABLE, 
    PRIMARY KEY (IFILTERID) ENABLE
);

CREATE TABLE AMS_FILTER_FILTERCONDITION
(
    IFILTERREF NUMBER(11,0), 
    iFilterConditionRef NUMBER(11,0), 
    IPOS NUMBER(11,0), 
    PRIMARY KEY (IFILTERREF, iFilterConditionRef) ENABLE
);

CREATE TABLE AMS_TOPIC
(
    ITOPICID NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CTOPICNAME VARCHAR2(128), 
    CNAME VARCHAR2(128), 
    CDESCRIPTION VARCHAR2(256), 
     PRIMARY KEY (ITOPICID) ENABLE
);

CREATE TABLE AMS_FILTERACTIONTYPE
(
    IFILTERACTIONTYPEID NUMBER(11,0) NOT NULL ENABLE, 
    CNAME VARCHAR2(128), 
    ITOPICREF NUMBER(11,0), 
    PRIMARY KEY (IFILTERACTIONTYPEID) ENABLE
);

CREATE TABLE AMS_FILTERACTION
(
    IFILTERACTIONID NUMBER(11,0) NOT NULL ENABLE, 
    IFILTERACTIONTYPEREF NUMBER(11,0) NOT NULL ENABLE, 
    IRECEIVERREF NUMBER(11,0), 
    CMESSAGE VARCHAR2(1024), 
    PRIMARY KEY (IFILTERACTIONID) ENABLE
);

CREATE TABLE AMS_FILTER_FILTERACTION
(
    IFILTERREF NUMBER(11,0) NOT NULL ENABLE, 
    IFILTERACTIONREF NUMBER(11,0) NOT NULL ENABLE, 
    IPOS NUMBER(11,0) NOT NULL ENABLE
);

CREATE TABLE AMS_FILTERCOND_PROPCOMPARE
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CMESSAGEKEYVALUE VARCHAR2(16) NOT NULL ENABLE, 
    SOPERATOR NUMBER(11,0), 
    CONSTRAINT AMS_FILTERCOND_PROPCOMPARE_PK PRIMARY KEY (iFilterConditionRef) ENABLE, 
    CONSTRAINT AMS_FILTERCOND_PROPCOMPARE_FK FOREIGN KEY (iFilterConditionRef)
      REFERENCES AMS_FILTERCONDITION (iFilterConditionId) ON DELETE CASCADE ENABLE
);

CREATE TABLE AMS_TBFILTER_FILTERCOND 
(
    IFILTERREF NUMBER(11,0) NOT NULL ENABLE, 
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    ITIMEBASEDCONDTYPE NUMBER NOT NULL ENABLE, 
    CONSTRAINT AMS_TBFILTER_FILTERCOND_FK FOREIGN KEY (IFILTERREF)
      REFERENCES AMS_FILTER (IFILTERID) ON DELETE CASCADE ENABLE, 
    CONSTRAINT AMS_TBFILTER_FILTERCOND_FK2 FOREIGN KEY (iFilterConditionRef)
      REFERENCES AMS_FILTERCONDITION (iFilterConditionId) ON DELETE CASCADE ENABLE
);

CREATE TABLE AMS_FILTER_TIMEBASED
(
    IFILTERREF NUMBER(11,0) NOT NULL ENABLE, 
    ITIMEOUT NUMBER(11,0) NOT NULL ENABLE, 
    ISTARTFILTERCONDITIONREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    ISTOPFILTERCONDITIONREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    ISENDONTIMEOUT NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
    CONSTRAINT AMS_FILTER_TIMEBASED_PK PRIMARY KEY (IFILTERREF) ENABLE, 
    CONSTRAINT AMS_FILTER_TIMEBASED_FK FOREIGN KEY (IFILTERREF)
      REFERENCES AMS_FILTER (IFILTERID) ON DELETE CASCADE ENABLE, 
    CONSTRAINT AMS_FILTER_TIMEBASED_FK3 FOREIGN KEY (ISTOPFILTERCONDITIONREF)
      REFERENCES AMS_FILTERCOND_JUNCTION (iFilterConditionRef) ENABLE, 
    CONSTRAINT AMS_FILTER_TIMEBASED_FK2 FOREIGN KEY (ISTARTFILTERCONDITIONREF)
      REFERENCES AMS_FILTERCOND_JUNCTION (iFilterConditionRef) ENABLE
);

CREATE TABLE AMS_FILTER_WATCHDOG
(
    IFILTERREF NUMBER(11,0) NOT NULL ENABLE, 
    ITIMEOUT NUMBER(11,0) NOT NULL ENABLE, 
    iFilterConditionRef NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CONSTRAINT AMS_FILTER_WATCHDOG_PK PRIMARY KEY (IFILTERREF) ENABLE, 
    CONSTRAINT AMS_FILTER_WATCHDOG_FK FOREIGN KEY (IFILTERREF)
      REFERENCES AMS_FILTER (IFILTERID) ON DELETE CASCADE ENABLE, 
    CONSTRAINT AMS_FILTER_WATCHDOG_FK2 FOREIGN KEY (iFilterConditionRef)
      REFERENCES AMS_FILTERCOND_JUNCTION (iFilterConditionRef) ENABLE
);

CREATE TABLE AMS_GROUPS
(
    IGROUPID NUMBER(11,0) NOT NULL ENABLE, 
    CGROUPNAME VARCHAR2(128), 
    STYPE NUMBER(6,0), 
    PRIMARY KEY (IGROUPID) ENABLE
);

CREATE TABLE AMS_DEFMESSAGETEXT
(
    IDEFMESSAGETEXTID NUMBER(11,0) NOT NULL ENABLE, 
    CNAME VARCHAR2(128) NOT NULL ENABLE, 
    CTEXT VARCHAR2(1024) NOT NULL ENABLE, 
    PRIMARY KEY (IDEFMESSAGETEXTID) ENABLE
);

CREATE TABLE AMS_FLAG
(
    CFLAGNAME VARCHAR2(32) NOT NULL ENABLE, 
    SFLAGVALUE NUMBER(6,0) NOT NULL ENABLE, 
    PRIMARY KEY (CFLAGNAME) ENABLE
);

--
-- Create Synchronisation Tables
--

CREATE TABLE AMS_USER_SYN
(
    IUSERID NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CUSERNAME VARCHAR2(128), 
    CEMAIL VARCHAR2(128), 
    CMOBILEPHONE VARCHAR2(64), 
    CPHONE VARCHAR2(64), 
    CSTATUSCODE VARCHAR2(32), 
    CCONFIRMCODE VARCHAR2(32), 
    SACTIVE NUMBER(6,0), 
    SPREFERREDALARMINGTYPERR NUMBER(6,0), 
    PRIMARY KEY (IUSERID) ENABLE
);

CREATE TABLE AMS_USERGROUP_USER_SYN
(
    IUSERGROUPREF NUMBER(11,0) NOT NULL ENABLE, 
    IUSERREF NUMBER(11,0) NOT NULL ENABLE, 
    IPOS NUMBER(11,0) NOT NULL ENABLE, 
    SACTIVE NUMBER(6,0), 
    CACTIVEREASON VARCHAR2(128), 
    TTIMECHANGE NUMBER(14,0), 
    PRIMARY KEY (IUSERGROUPREF, IUSERREF) ENABLE
);

CREATE TABLE AMS_FILTERCONDITIONTYPE_SYN
(
    IFILTERCONDITIONTYPEID NUMBER(11,0), 
    CNAME VARCHAR2(128), 
    CCLASS VARCHAR2(256), 
    CCLASSUI VARCHAR2(256), 
    PRIMARY KEY (IFILTERCONDITIONTYPEID) ENABLE
);

CREATE TABLE AMS_FILTERCONDITION_SYN
(
    iFilterConditionId NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CNAME VARCHAR2(128), 
    CDESC VARCHAR2(256), 
    IFILTERCONDITIONTYPEREF NUMBER(11,0), 
    PRIMARY KEY (iFilterConditionId) ENABLE
);

CREATE TABLE AMS_FILTERCONDITION_STRING_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CKEYVALUE VARCHAR2(16), 
    SOPERATOR NUMBER(6,0), 
    CCOMPVALUE VARCHAR2(128)
);

CREATE TABLE AMS_FILTERCOND_ARRSTR_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CKEYVALUE VARCHAR2(16), 
    SOPERATOR NUMBER(6,0)
);

CREATE TABLE AMS_FILTERCOND_ARRSTRVAL_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CCOMPVALUE VARCHAR2(128)
);

CREATE TABLE AMS_FILTERCOND_TIMEBASED_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CSTARTKEYVALUE VARCHAR2(16), 
    SSTARTOPERATOR NUMBER(6,0), 
    CSTARTCOMPVALUE VARCHAR2(128), 
    CCONFIRMKEYVALUE VARCHAR2(16), 
    SCONFIRMOPERATOR NUMBER(6,0), 
    CCONFIRMCOMPVALUE VARCHAR2(128), 
    STIMEPERIOD NUMBER(6,0), 
    STIMEBEHAVIOR NUMBER(6,0)
);

CREATE TABLE AMS_FILTERCONDITION_PV_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CPVCHANNELNAME VARCHAR2(128), 
    SSUGGESTEDPVTYPEID NUMBER(6,0), 
    SOPERATORID NUMBER(6,0), 
    CCOMPVALUE VARCHAR2(128)
);

CREATE TABLE AMS_FILTERCOND_CONJ_COMMON_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    IFIRSTFILTERCONDITIONREF NUMBER(11,0) NOT NULL ENABLE, 
    ISECONDFILTERCONDITIONREF NUMBER(11,0) NOT NULL ENABLE, 
    IOPERAND NUMBER(6,0) DEFAULT 0
);

CREATE TABLE AMS_FILTERCOND_JUNCTION_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    operator VARCHAR2(3) NOT NULL ENABLE
);

CREATE TABLE AMS_FILTERCOND_FILTERCOND_SYN
(
    iFilterConditionId NUMBER(11,0) NOT NULL ENABLE, 
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE
);

CREATE TABLE AMS_FILTERCOND_NEGATION_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    INEGATEDFCREF NUMBER(11,0) NOT NULL ENABLE
);

CREATE TABLE AMS_FILTER_SYN
(
    IFILTERID NUMBER(11,0), 
    IGROUPREF NUMBER(11,0) NOT NULL ENABLE, 
    CNAME VARCHAR2(128), 
    CDEFAULTMESSAGE VARCHAR2(1024), 
    CFILTERTYPE VARCHAR2(100) NOT NULL ENABLE
);

CREATE TABLE AMS_FILTER_FILTERCONDITION_SYN
(
    IFILTERREF NUMBER(11,0), 
    iFilterConditionRef NUMBER(11,0), 
    IPOS NUMBER(11,0), 
    PRIMARY KEY (IFILTERREF, iFilterConditionRef) ENABLE
);

CREATE TABLE AMS_TOPIC_SYN
(
    ITOPICID NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CTOPICNAME VARCHAR2(128), 
    CNAME VARCHAR2(128), 
    CDESCRIPTION VARCHAR2(256), 
    PRIMARY KEY (ITOPICID) ENABLE
);

CREATE TABLE AMS_FILTERACTIONTYPE_SYN
(
    IFILTERACTIONTYPEID NUMBER(11,0) NOT NULL ENABLE, 
    CNAME VARCHAR2(128), 
    ITOPICREF NUMBER(11,0), 
    PRIMARY KEY (IFILTERACTIONTYPEID) ENABLE
);

CREATE TABLE AMS_FILTERACTION_SYN
(
    IFILTERACTIONID NUMBER(11,0) NOT NULL ENABLE, 
    IFILTERACTIONTYPEREF NUMBER(11,0) NOT NULL ENABLE, 
    IRECEIVERREF NUMBER(11,0), 
    CMESSAGE VARCHAR2(1024), 
    PRIMARY KEY (IFILTERACTIONID) ENABLE
);

CREATE TABLE AMS_FILTER_FILTERACTION_SYN
(
    IFILTERREF NUMBER(11,0) NOT NULL ENABLE, 
    IFILTERACTIONREF NUMBER(11,0) NOT NULL ENABLE, 
    IPOS NUMBER(11,0) NOT NULL ENABLE
);

CREATE TABLE AMS_USERGROUP_SYN
(
    IUSERGROUPID NUMBER(11,0) NOT NULL ENABLE, 
    IGROUPREF NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
    CUSERGROUPNAME VARCHAR2(128), 
    SMINGROUPMEMBER NUMBER(6,0), 
    ITIMEOUTSEC NUMBER(11,0), 
    SACTIVE NUMBER(6,0), 
    PRIMARY KEY (IUSERGROUPID) ENABLE
);

CREATE TABLE AMS_FILTERCOND_PROPCOMPARE_SYN
(
    iFilterConditionRef NUMBER(11,0) NOT NULL ENABLE, 
    CMESSAGEKEYVALUE VARCHAR2(16) NOT NULL ENABLE, 
    SOPERATOR NUMBER(11,0)
);

CREATE TABLE AMS_FILTER_TIMEBASED_SYN
(
    IFILTERREF NUMBER(11,0) NOT NULL ENABLE, 
    ITIMEOUT NUMBER(11,0) NOT NULL ENABLE, 
    ISTARTFILTERCONDITIONREF NUMBER(11,0) NOT NULL ENABLE, 
    ISTOPFILTERCONDITIONREF NUMBER(11,0) NOT NULL ENABLE,
    ISENDONTIMEOUT NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
);

CREATE TABLE AMS_FILTER_WATCHDOG_SYN
(
    IFILTERREF NUMBER(11,0) NOT NULL ENABLE, 
    ITIMEOUT NUMBER(11,0) NOT NULL ENABLE, 
    iFilterConditionRef NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE
);

DROP SEQUENCE  AMS_FILTERACTION_ID;
CREATE SEQUENCE  AMS_FILTERACTION_ID  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

DROP SEQUENCE  AMS_FILTERCONDITION_ID;
CREATE SEQUENCE  AMS_FILTERCONDITION_ID  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

DROP SEQUENCE  AMS_FILTERTYPE_ID;
CREATE SEQUENCE  AMS_FILTERTYPE_ID  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

DROP SEQUENCE  AMS_FILTER_ID;
CREATE SEQUENCE  AMS_FILTER_ID  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

DROP SEQUENCE  AMS_GROUPS_ID;
CREATE SEQUENCE  AMS_GROUPS_ID  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

DROP SEQUENCE  AMS_TOPIC_ID;
CREATE SEQUENCE  AMS_TOPIC_ID  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

DROP SEQUENCE  AMS_USERGROUP_ID;
CREATE SEQUENCE  AMS_USERGROUP_ID  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

DROP SEQUENCE  AMS_USER_ID;
CREATE SEQUENCE  AMS_USER_ID  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER  NOCYCLE;


INSERT INTO AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (1,'Stringbasiert','org.csstudio.ams.filter.FilterConditionString','org.csstudio.ams.filter.ui.FilterConditionStringUI');
INSERT INTO AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (2,'Zeitbasiert','org.csstudio.ams.filter.FilterConditionTimeBased','org.csstudio.ams.filter.ui.FilterConditionTimeBasedUI');
INSERT INTO AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (3,'Stringbasiert (Array)','org.csstudio.ams.filter.FilterConditionArrayString','org.csstudio.ams.filter.ui.FilterConditionArrayStringUI');
INSERT INTO AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (4,'PV-basiert','org.csstudio.ams.filter.FilterConditionProcessVariable','org.csstudio.ams.filter.ui.FilterConditionProcessVariableUI');
INSERT INTO AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (5,'Oder-Verknuepft','org.csstudio.ams.filter.FilterConditionOrConjunction','org.csstudio.ams.filter.ui.FilterConditionOrConjunctionUI');

INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (1,'SMS an Person',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (2,'SMS an Gruppe',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (3,'SMS an Gruppe Best.',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (4,'VMail an Person',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (5,'VMail an Gruppe',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (6,'VMail an Gruppe Best.',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (7,'EMail an Person',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (8,'EMail an Gruppe',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (9,'EMail an Gruppe Best.',NULL);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (10,'Message an Topic',NULL);

INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (100,'Topic Special Log',1);
INSERT INTO AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (101,'Topic 101',2);

-- INSERT INTO AMS_Topic (iTopicID,cName,cUrl,cPort,cProtocol) values (1,'T_AMS_FREE_100','localhost','1099','rmi');
-- INSERT INTO AMS_Topic (iTopicID,cName,cUrl,cPort,cProtocol) values (2,'T_AMS_FREE_101','localhost','1099','rmi');

INSERT INTO AMS_Flag (cFlagName, sFlagValue) values ('BupState', 0);

COMMIT;
