CREATE TABLE  "AMS_DEFMESSAGETEXT" 
   (	"IDEFMESSAGETEXTID" NUMBER(11,0) NOT NULL ENABLE, 
	"CNAME" VARCHAR2(128) NOT NULL ENABLE, 
	"CTEXT" VARCHAR2(1024) NOT NULL ENABLE, 
	 PRIMARY KEY ("IDEFMESSAGETEXTID") ENABLE
   );

CREATE TABLE  "AMS_FILTER" 
   (	"IFILTERID" NUMBER(11,0), 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CNAME" VARCHAR2(128), 
	"CDEFAULTMESSAGE" VARCHAR2(1024), 
	"CFILTERTYPE" VARCHAR2(100) DEFAULT 'default' NOT NULL ENABLE, 
	 PRIMARY KEY ("IFILTERID") ENABLE
   );

CREATE TABLE  "AMS_FILTERACTION" 
   (	"IFILTERACTIONID" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERACTIONTYPEREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IRECEIVERREF" NUMBER(11,0), 
	"CMESSAGE" VARCHAR2(1024), 
	 PRIMARY KEY ("IFILTERACTIONID") ENABLE
   );

CREATE TABLE  "AMS_FILTERACTION_SYN" 
   (	"IFILTERACTIONID" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERACTIONTYPEREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IRECEIVERREF" NUMBER(11,0), 
	"CMESSAGE" VARCHAR2(1024), 
	 PRIMARY KEY ("IFILTERACTIONID") ENABLE
   );

CREATE TABLE  "AMS_FILTERACTIONTYPE" 
   (	"IFILTERACTIONTYPEID" NUMBER(11,0) NOT NULL ENABLE, 
	"CNAME" VARCHAR2(128), 
	"ITOPICREF" NUMBER(11,0), 
	 PRIMARY KEY ("IFILTERACTIONTYPEID") ENABLE
   );

CREATE TABLE  "AMS_FILTERACTIONTYPE_SYN" 
   (	"IFILTERACTIONTYPEID" NUMBER(11,0) NOT NULL ENABLE, 
	"CNAME" VARCHAR2(128), 
	"ITOPICREF" NUMBER(11,0), 
	 PRIMARY KEY ("IFILTERACTIONTYPEID") ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_ARRSTR" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CKEYVALUE" VARCHAR2(16), 
	"SOPERATOR" NUMBER(6,0)
   );

CREATE TABLE  "AMS_FILTERCOND_ARRSTR_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CKEYVALUE" VARCHAR2(16), 
	"SOPERATOR" NUMBER(6,0)
   );

CREATE TABLE  "AMS_FILTERCOND_ARRSTRVAL" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CCOMPVALUE" VARCHAR2(128)
   );

CREATE TABLE  "AMS_FILTERCOND_ARRSTRVAL_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CCOMPVALUE" VARCHAR2(128)
   );

CREATE TABLE  "AMS_FILTERCOND_CONJ_COMMON" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IFIRSTFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ISECONDFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IOPERAND" NUMBER(6,0)
   );

CREATE TABLE  "AMS_FILTERCOND_CONJ_COMMON_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IFIRSTFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ISECONDFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IOPERAND" NUMBER(6,0) DEFAULT 0
   );

CREATE TABLE  "AMS_FILTERCOND_FILTERCOND" 
   (	"IFILTERCONDITIONID" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_FILTERCOND_SYN" 
   (	"IFILTERCONDITIONID" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTERCONDITION" 
   (	"IFILTERCONDITIONID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CNAME" VARCHAR2(128), 
	"CDESC" VARCHAR2(256), 
	"IFILTERCONDITIONTYPEREF" NUMBER(11,0), 
	 PRIMARY KEY ("IFILTERCONDITIONID") ENABLE
   );

CREATE TABLE  "AMS_FILTERCONDITION_PV" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CPVCHANNELNAME" VARCHAR2(128), 
	"SSUGGESTEDPVTYPEID" NUMBER(6,0), 
	"SOPERATORID" NUMBER(6,0), 
	"CCOMPVALUE" VARCHAR2(128)
   );

CREATE TABLE  "AMS_FILTERCONDITION_PV_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CPVCHANNELNAME" VARCHAR2(128), 
	"SSUGGESTEDPVTYPEID" NUMBER(6,0), 
	"SOPERATORID" NUMBER(6,0), 
	"CCOMPVALUE" VARCHAR2(128)
   );

CREATE TABLE  "AMS_FILTERCONDITION_STRING" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CKEYVALUE" VARCHAR2(16), 
	"SOPERATOR" NUMBER(6,0), 
	"CCOMPVALUE" VARCHAR2(128)
   );

CREATE TABLE  "AMS_FILTERCONDITION_STRING_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CKEYVALUE" VARCHAR2(16), 
	"SOPERATOR" NUMBER(6,0), 
	"CCOMPVALUE" VARCHAR2(128)
   );

CREATE TABLE  "AMS_FILTERCONDITION_SYN" 
   (	"IFILTERCONDITIONID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CNAME" VARCHAR2(128), 
	"CDESC" VARCHAR2(256), 
	"IFILTERCONDITIONTYPEREF" NUMBER(11,0), 
	 PRIMARY KEY ("IFILTERCONDITIONID") ENABLE
   );

CREATE TABLE  "AMS_FILTERCONDITIONTYPE" 
   (	"IFILTERCONDITIONTYPEID" NUMBER(11,0), 
	"CNAME" VARCHAR2(128), 
	"CCLASS" VARCHAR2(256), 
	"CCLASSUI" VARCHAR2(256), 
	 PRIMARY KEY ("IFILTERCONDITIONTYPEID") ENABLE
   );

CREATE TABLE  "AMS_FILTERCONDITIONTYPE_SYN" 
   (	"IFILTERCONDITIONTYPEID" NUMBER(11,0), 
	"CNAME" VARCHAR2(128), 
	"CCLASS" VARCHAR2(256), 
	"CCLASSUI" VARCHAR2(256), 
	 PRIMARY KEY ("IFILTERCONDITIONTYPEID") ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_JUNCTION" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"OPERATOR" VARCHAR2(3) NOT NULL ENABLE, 
	 CONSTRAINT "AMS_FILTERCOND_JUNCTION_CON" PRIMARY KEY ("IFILTERCONDITIONREF") ENABLE, 
	 CONSTRAINT "AMS_FILTERCOND_JUNCTION_FK" FOREIGN KEY ("IFILTERCONDITIONREF");
	  REFERENCES  "AMS_FILTERCONDITION" ("IFILTERCONDITIONID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_JUNCTION_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"OPERATOR" VARCHAR2(3) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_NEGATION" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"INEGATEDFCREF" NUMBER(11,0) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_NEGATION_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"INEGATEDFCREF" NUMBER(11,0) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_PROPCOMPARE" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CMESSAGEKEYVALUE" VARCHAR2(16) NOT NULL ENABLE, 
	"SOPERATOR" NUMBER(11,0), 
	 CONSTRAINT "AMS_FILTERCOND_PROPCOMPARE_PK" PRIMARY KEY ("IFILTERCONDITIONREF") ENABLE, 
	 CONSTRAINT "AMS_FILTERCOND_PROPCOMPARE_FK" FOREIGN KEY ("IFILTERCONDITIONREF");
	  REFERENCES  "AMS_FILTERCONDITION" ("IFILTERCONDITIONID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE  "AMS_FILTERCOND_PROPCOMPARE_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CMESSAGEKEYVALUE" VARCHAR2(16) NOT NULL ENABLE, 
	"SOPERATOR" NUMBER(11,0)
   );

CREATE TABLE  "AMS_FILTERCOND_TIMEBASED" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CSTARTKEYVALUE" VARCHAR2(16), 
	"SSTARTOPERATOR" NUMBER(6,0), 
	"CSTARTCOMPVALUE" VARCHAR2(128), 
	"CCONFIRMKEYVALUE" VARCHAR2(16), 
	"SCONFIRMOPERATOR" NUMBER(6,0), 
	"CCONFIRMCOMPVALUE" VARCHAR2(128), 
	"STIMEPERIOD" NUMBER(6,0), 
	"STIMEBEHAVIOR" NUMBER(6,0)
   );

CREATE TABLE  "AMS_FILTERCOND_TIMEBASED_SYN" 
   (	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CSTARTKEYVALUE" VARCHAR2(16), 
	"SSTARTOPERATOR" NUMBER(6,0), 
	"CSTARTCOMPVALUE" VARCHAR2(128), 
	"CCONFIRMKEYVALUE" VARCHAR2(16), 
	"SCONFIRMOPERATOR" NUMBER(6,0), 
	"CCONFIRMCOMPVALUE" VARCHAR2(128), 
	"STIMEPERIOD" NUMBER(6,0), 
	"STIMEBEHAVIOR" NUMBER(6,0)
   );

CREATE TABLE  "AMS_FILTER_FILTERACTION" 
   (	"IFILTERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERACTIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IPOS" NUMBER(11,0) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTER_FILTERACTION_SYN" 
   (	"IFILTERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERACTIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IPOS" NUMBER(11,0) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTER_FILTERCONDITION" 
   (	"IFILTERREF" NUMBER(11,0), 
	"IFILTERCONDITIONREF" NUMBER(11,0), 
	"IPOS" NUMBER(11,0), 
	 PRIMARY KEY ("IFILTERREF", "IFILTERCONDITIONREF") ENABLE
   );

CREATE TABLE  "AMS_FILTER_FILTERCONDITION_SYN" 
   (	"IFILTERREF" NUMBER(11,0), 
	"IFILTERCONDITIONREF" NUMBER(11,0), 
	"IPOS" NUMBER(11,0), 
	 PRIMARY KEY ("IFILTERREF", "IFILTERCONDITIONREF") ENABLE
   );

CREATE TABLE  "AMS_FILTER_SYN" 
   (	"IFILTERID" NUMBER(11,0), 
	"IGROUPREF" NUMBER(11,0) NOT NULL ENABLE, 
	"CNAME" VARCHAR2(128), 
	"CDEFAULTMESSAGE" VARCHAR2(1024), 
	"CFILTERTYPE" VARCHAR2(100) NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTER_TIMEBASED" 
   (	"IFILTERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ITIMEOUT" NUMBER(11,0) NOT NULL ENABLE, 
	"ISTARTFILTERCONDITIONREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"ISTOPFILTERCONDITIONREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"ISENDONTIMEOUT" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "AMS_FILTER_TIMEBASED_PK" PRIMARY KEY ("IFILTERREF") ENABLE, 
	 CONSTRAINT "AMS_FILTER_TIMEBASED_FK" FOREIGN KEY ("IFILTERREF")
	  REFERENCES  "AMS_FILTER" ("IFILTERID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "AMS_FILTER_TIMEBASED_FK3" FOREIGN KEY ("ISTOPFILTERCONDITIONREF")
	  REFERENCES  "AMS_FILTERCOND_JUNCTION" ("IFILTERCONDITIONREF") ENABLE, 
	 CONSTRAINT "AMS_FILTER_TIMEBASED_FK2" FOREIGN KEY ("ISTARTFILTERCONDITIONREF")
	  REFERENCES  "AMS_FILTERCOND_JUNCTION" ("IFILTERCONDITIONREF") ENABLE
   );

CREATE TABLE  "AMS_FILTER_TIMEBASED_SYN" 
   (	"IFILTERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ITIMEOUT" NUMBER(11,0) NOT NULL ENABLE, 
	"ISTARTFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ISTOPFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE,
	"ISENDONTIMEOUT" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FILTER_WATCHDOG" 
   (	"IFILTERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ITIMEOUT" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERCONDITIONREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	 CONSTRAINT "AMS_FILTER_WATCHDOG_PK" PRIMARY KEY ("IFILTERREF") ENABLE, 
	 CONSTRAINT "AMS_FILTER_WATCHDOG_FK" FOREIGN KEY ("IFILTERREF")
	  REFERENCES  "AMS_FILTER" ("IFILTERID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "AMS_FILTER_WATCHDOG_FK2" FOREIGN KEY ("IFILTERCONDITIONREF")
	  REFERENCES  "AMS_FILTERCOND_JUNCTION" ("IFILTERCONDITIONREF") ENABLE
   );

CREATE TABLE  "AMS_FILTER_WATCHDOG_SYN" 
   (	"IFILTERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ITIMEOUT" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERCONDITIONREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE
   );

CREATE TABLE  "AMS_FLAG" 
   (	"CFLAGNAME" VARCHAR2(32) NOT NULL ENABLE, 
	"SFLAGVALUE" NUMBER(6,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("CFLAGNAME") ENABLE
   );

CREATE TABLE  "AMS_GROUPS" 
   (	"IGROUPID" NUMBER(11,0) NOT NULL ENABLE, 
	"CGROUPNAME" VARCHAR2(128), 
	"STYPE" NUMBER(6,0), 
	 PRIMARY KEY ("IGROUPID") ENABLE
   );

CREATE TABLE  "AMS_TBFILTER_FILTERCOND" 
   (	"IFILTERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IFILTERCONDITIONREF" NUMBER(11,0) NOT NULL ENABLE, 
	"ITIMEBASEDCONDTYPE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "AMS_TBFILTER_FILTERCOND_FK" FOREIGN KEY ("IFILTERREF")
	  REFERENCES  "AMS_FILTER" ("IFILTERID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "AMS_TBFILTER_FILTERCOND_FK2" FOREIGN KEY ("IFILTERCONDITIONREF")
	  REFERENCES  "AMS_FILTERCONDITION" ("IFILTERCONDITIONID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE  "AMS_TOPIC" 
   (	"ITOPICID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CTOPICNAME" VARCHAR2(128), 
	"CNAME" VARCHAR2(128), 
	"CDESCRIPTION" VARCHAR2(256), 
	 PRIMARY KEY ("ITOPICID") ENABLE
   );

CREATE TABLE  "AMS_TOPIC_SYN" 
   (	"ITOPICID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CTOPICNAME" VARCHAR2(128), 
	"CNAME" VARCHAR2(128), 
	"CDESCRIPTION" VARCHAR2(256), 
	 PRIMARY KEY ("ITOPICID") ENABLE
   );

CREATE TABLE  "AMS_USER" 
   (	"IUSERID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CUSERNAME" VARCHAR2(128), 
	"CEMAIL" VARCHAR2(128), 
	"CMOBILEPHONE" VARCHAR2(64), 
	"CPHONE" VARCHAR2(64), 
	"CSTATUSCODE" VARCHAR2(32), 
	"CCONFIRMCODE" VARCHAR2(32), 
	"SACTIVE" NUMBER(6,0), 
	"SPREFERREDALARMINGTYPERR" NUMBER(6,0), 
	 PRIMARY KEY ("IUSERID") ENABLE
   );

CREATE TABLE  "AMS_USERGROUP" 
   (	"IUSERGROUPID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CUSERGROUPNAME" VARCHAR2(128), 
	"SMINGROUPMEMBER" NUMBER(6,0), 
	"ITIMEOUTSEC" NUMBER(11,0), 
	"SACTIVE" NUMBER(6,0), 
	 PRIMARY KEY ("IUSERGROUPID") ENABLE
   );

CREATE TABLE  "AMS_USERGROUP_SYN" 
   (	"IUSERGROUPID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CUSERGROUPNAME" VARCHAR2(128), 
	"SMINGROUPMEMBER" NUMBER(6,0), 
	"ITIMEOUTSEC" NUMBER(11,0), 
	"SACTIVE" NUMBER(6,0), 
	 PRIMARY KEY ("IUSERGROUPID") ENABLE
   );

CREATE TABLE  "AMS_USERGROUP_USER" 
   (	"IUSERGROUPREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IUSERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IPOS" NUMBER(11,0) NOT NULL ENABLE, 
	"SACTIVE" NUMBER(6,0), 
	"CACTIVEREASON" VARCHAR2(128), 
	"TTIMECHANGE" NUMBER(14,0), 
	 PRIMARY KEY ("IUSERGROUPREF", "IUSERREF") ENABLE
   );

CREATE TABLE  "AMS_USERGROUP_USER_SYN" 
   (	"IUSERGROUPREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IUSERREF" NUMBER(11,0) NOT NULL ENABLE, 
	"IPOS" NUMBER(11,0) NOT NULL ENABLE, 
	"SACTIVE" NUMBER(6,0), 
	"CACTIVEREASON" VARCHAR2(128), 
	"TTIMECHANGE" NUMBER(14,0), 
	 PRIMARY KEY ("IUSERGROUPREF", "IUSERREF") ENABLE
   );

CREATE TABLE  "AMS_USER_SYN" 
   (	"IUSERID" NUMBER(11,0) NOT NULL ENABLE, 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CUSERNAME" VARCHAR2(128), 
	"CEMAIL" VARCHAR2(128), 
	"CMOBILEPHONE" VARCHAR2(64), 
	"CPHONE" VARCHAR2(64), 
	"CSTATUSCODE" VARCHAR2(32), 
	"CCONFIRMCODE" VARCHAR2(32), 
	"SACTIVE" NUMBER(6,0), 
	"SPREFERREDALARMINGTYPERR" NUMBER(6,0), 
	 PRIMARY KEY ("IUSERID") ENABLE
   );

CREATE TABLE  "AMS_MSG_EXT_PVS" 
(	
	"ID" NUMBER(11,0), 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CPVNAME" VARCHAR2(128) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "AMS_MSG_EXT_PVS_UNIQUE" UNIQUE ("CPVNAME") ENABLE
);

CREATE TABLE  "AMS_MSG_EXT_PVS_SYN" 
(	
	"ID" NUMBER(11,0), 
	"IGROUPREF" NUMBER(11,0) DEFAULT -1 NOT NULL ENABLE, 
	"CPVNAME" VARCHAR2(128) NOT NULL ENABLE 
);

CREATE TABLE  AMS_MSG_EXTENSIONS
(	
	IDREF NUMBER(11,0)  NOT NULL, 
	CMESSAGEKEY VARCHAR2(4000) NOT NULL, 
	CMESSAGEVALUE VARCHAR2(4000) NOT NULL,
	CONSTRAINT "AMS_MSG_EXTENSIONS_CON" FOREIGN KEY ("IDREF") 
	 REFERENCES  "AMS_MSG_EXT_PVS" ("ID") ON DELETE CASCADE ENABLE
);

CREATE TABLE  AMS_MSG_EXTENSIONS_SYN
(	
	IDREF NUMBER(11,0)  NOT NULL, 
	CMESSAGEKEY VARCHAR2(4000) NOT NULL, 
	CMESSAGEVALUE VARCHAR2(4000) NOT NULL
);

 CREATE SEQUENCE   "AMS_FILTERACTION_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2418 CACHE 20 NOORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_FILTERCONDITION_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3570 CACHE 20 NOORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_FILTERTYPE_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_FILTER_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1830 CACHE 20 NOORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_GROUPS_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 500 CACHE 20 NOORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_TOPIC_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 521 CACHE 20 NOORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_USERGROUP_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 323 CACHE 20 NOORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_USER_ID"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 485 CACHE 20 ORDER  NOCYCLE;

 CREATE SEQUENCE   "AMS_MSG_EXT_ID"  MINVALUE 0 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE;

insert into AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (1,'Stringbasiert','org.csstudio.ams.filter.FilterConditionString','org.csstudio.ams.filter.ui.FilterConditionStringUI');
insert into AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (2,'Zeitbasiert','org.csstudio.ams.filter.FilterConditionTimeBased','org.csstudio.ams.filter.ui.FilterConditionTimeBasedUI');
insert into AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (3,'Stringbasiert (Array)','org.csstudio.ams.filter.FilterConditionArrayString','org.csstudio.ams.filter.ui.FilterConditionArrayStringUI');
insert into AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (4,'PV-basiert','org.csstudio.ams.filter.FilterConditionProcessVariable','org.csstudio.ams.filter.ui.FilterConditionProcessVariableUI');
insert into AMS_FilterConditionType (iFilterConditionTypeID,cName,cClass,cClassUI) values (5,'Oder-Verknuepft','org.csstudio.ams.filter.FilterConditionOrConjunction','org.csstudio.ams.filter.ui.FilterConditionOrConjunctionUI');

insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (1,'SMS an Person',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (2,'SMS an Gruppe',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (3,'SMS an Gruppe Best.',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (4,'VMail an Person',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (5,'VMail an Gruppe',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (6,'VMail an Gruppe Best.',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (7,'EMail an Person',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (8,'EMail an Gruppe',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (9,'EMail an Gruppe Best.',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (10,'Message an Topic',NULL);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (11,'Erweiterte Message an Topic',NULL);

insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (100,'Topic Special Log',1);
insert into AMS_FilterActionType (iFilterActionTypeID,cName,iTopicRef) values (101,'Topic 101',2);

-- insert into AMS_Topic (iTopicID,cName,cUrl,cPort,cProtocol) values (1,'T_AMS_FREE_100','localhost','1099','rmi');
-- insert into AMS_Topic (iTopicID,cName,cUrl,cPort,cProtocol) values (2,'T_AMS_FREE_101','localhost','1099','rmi');

insert into AMS_Flag (cFlagName, sFlagValue) values ('BupState', 0);

commit;